### ISSUE TITLE
Affection Status as Extension to Individual vs Standalone Observation

### ISSUE THREAD

**Issue by liberaliscomputing** [ga4gh-cp/pedigree-fhir-ig#1]
@ametke built [Affected Status](https://ga4gh-cp.github.io/pedigree-fhir-ig/StructureDefinition-AffectedStatus.html) off of [Observation](http://hl7.org/fhir/R4/observation.html) whereas @liberaliscomputing considered [Affected](https://liberaliscomputing.github.io/pedigree-fhir-ig/StructureDefinition-affected.html) as Extension to Patient. Let's discuss pros and cons of these approaches in modeling [Individual](https://github.com/ga4gh-cp/pedigree/blob/master/model.md#individual)'s `affected` property.

**Comment by ametke** [comment]
I see two advantages in the Observation approach. First, it avoids the creation of an extension. Even though FHIR was designed with extensibility in mind and extensions are not frowned upon, it is usually preferable to avoid the use of extensions whenever possible (this is stated as a specific goal in some HL7 working groups, e.g. Clinical Genomics), i.e., when there is an equivalent way of representing the same thing. The second advantage is that it decouples the affected status from the Patient resource, which I think is benefitial because the attribute on its own, in a context other than a pedigree, won't make sense.

**Comment by liberaliscomputing** [comment]
@ametke, I can't agree more with you that avoiding the creation of unnecessary extensions better guarantees interoperability.

Why I rendered it as an extension to Individual is that 1) I aimed to reflect the model as it is (https://github.com/ga4gh-cp/pedigree/blob/master/model.md#individual) and 2) I didn't fully understand the meaning of "included for PED backwards compatibility" in the doc (I need further clarification from @buske).

And yeah, the affection status only has a meaning within a condition as a specific context. If `affected` is bound to Individual, then it would need to be a complex type having an attribute indicating affected of what. But, even with this approach, I would also argue that we need to decouple the affection status of a specific condition from Individual (since having a condition is not a meta-essence of Individual).

So, a long story short, yeah, I am down for the idea of modeling affection status as Observation!
